### ISSUE TITLE
Сервисы для связи

### ISSUE THREAD

**Issue by kvpbldsck** [pavelzaitsau/awesome-travel#1]
Я тут узнал про существование Airalo: приложение для покупки eSIM-ок с интернетом в куче стран. Еще есть DrimSIM. Можно указать добавить в список

**Comment by pavelzaitsau** [comment]
@ikonvpalto Welcome to pr :)

**Comment by pavelzaitsau** [comment]
https://github.com/pavelzaitsau/awesome-travel/commit/1579ccb449da26a470c5128f855a609025e87ad3
